config/routes.rb
Rails.application.routes.draw do
  get 'admin/index' => 'admin/captains#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :whalers

  namespace :admin do
    resources :captains do
      member do
        post 'flip_feature'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/captain.rb
class Captain < ApplicationRecord
  def features
    ROLLOUT.features.map { |feature|
      [feature, {
        status: ROLLOUT.active?(feature, self),
        data:   ROLLOUT.get(feature).data,
      }]
    }.to_h
  end

  def rollout_flip_features(feature_params)
    feature_params.each do |feature, flip|
      rollout_update_feature(feature.to_sym, flip == '1')
    end
  end

  def rollout_update_feature(feature, flip)
    raise "#{feature} is not a valid feature." unless ROLLOUT.features.include?(feature)

    if flip
      logger.info "activating #{feature} for Captain #{name}"
      ROLLOUT.activate_user(feature, self)
    else
      logger.info "deactivating #{feature} for Captain #{name}"
      ROLLOUT.deactivate_user(feature, self)
    end
    flip
  rescue => e
    raise "There was an issue flipping #{feature} for #{name}"
  end
end

app/models/whaler.rb
class Whaler < ApplicationRecord
  def recruit_score
    (strength/1.1 * skill).ceil
  end
end

app/controllers/admin/captains_controller.rb
class Admin::CaptainsController < AdminController
  before_action :find_captain, only: [ :show, :flip_feature ]
  def index
    @captains = Captain.all
  end

  def show
    @features = @captain.features
  end

  def flip_feature
    if @captain.rollout_flip_features(admin_captain_feature_flipping_params)
    redirect_to [:admin, @captain], flash: { success: feature_flipped_success_message }
  else
    redirect_to [:admin, @captain], flash: { warning: 'There was a problem with feature flipping.' }
  end
  end

  protected

  def find_captain
    @captain = Captain.find_by(id: params[:id])
  end

  private

  def feature_flipped_success_message
    # 'Mug Shot' turned off
    msg = 'Sucess! '
    admin_captain_feature_flipping_params.each do |feature, flip|
      feature_name = ROLLOUT.get(feature).data['name']
      status       = (flip != '1') ? 'off' : 'on'
      msg         += "#{feature_name} turned #{status}"
    end
    msg
  end

  def admin_captain_feature_flipping_params
    params.require(:features)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/whalers_controller.rb
# frozen_string_literal: true

class WhalersController < ApplicationController
  before_action :find_whaler
  before_action :find_current_captain
  layout 'whaler'

  def show; end

  protected

  def find_whaler
    @whaler = Whaler.find_by(id: params[:id])
  end

  def find_current_captain
    @captain = Captain.find_by(id: 2)
  end
end

app/helpers/admin/captains_controller_helper.rb
module Admin::CaptainsControllerHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def whaler_image_activated?(captain)
    ROLLOUT.active?(:whaler_image, captain)
  end

  def recruitment_activated?(captain)
    ROLLOUT.active?(:recruit, captain)
  end

end

app/helpers/whaler_helper.rb
module WhalerHelper
end

app/views/admin/captains/_captain.html.erb
<li>
  
</li>

app/views/admin/captains/index.html.erb
<h2>Captains</h2>

list of captains

<ul>
  <% @captains.each do |captain| %>
    <li>
      <%= link_to captain.name, admin_captain_path(captain) %>
    </li>
  <% end %>
</ul>

app/views/admin/captains/show.html.erb
<h3><%= @captain.name %></h3>

<h4>Dashboard Features</h4>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "toast toast-#{name}" %>
<% end -%>

<table>
  <% @features.each do |feature, details| %>
    <tr>
      <td width="25%">
        <%= details[:data]["name"] || feature.to_s %>
      </td>
      <td>
        <%= form_for :features, url: flip_feature_admin_captain_path(@captain), method: :post, html: {class: 'm-0'} do |f| %>
          <label class="form-switch">
            <%= f.check_box feature, {onchange: 'this.form.submit();', checked: details[:status] } %>
            <i class="form-icon"></i>
          </label>

        <% end %>
      </td>
      <td>
        <small>
          <%= details[:data]["description"] %>
        </small>
      </td>
    </tr>
  <% end %>
</table>

app/views/common/_header.html.erb
<header class="navbar bg-dark text-light">
  <section class="navbar-section">
    <a href="#" class="btn btn-link text-light">Docs</a>
    <a href="#" class="btn btn-link text-light">Examples</a>
  </section>
  <section class="navbar-center">
    header!
  </section>
  <section class="navbar-section mr-2">
    <a href="" class="text-light">Captain <%= @captain.name %></a>
  </section>
</header>

app/views/common/_header_admin.html.erb
<header class="navbar">
  <section class="navbar-section">
    <a href="#" class="btn btn-link">Docs</a>
    <a href="#" class="btn btn-link">Examples</a>
  </section>
  <section class="navbar-center">
    admin dashboard!
  </section>
  <section class="navbar-section">
    <a href="#" class="btn btn-link">Twitter</a>
    <a href="#" class="btn btn-link">GitHub</a>
  </section>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobyflip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/header_admin' %>
    <div class="pad"></div>
    <div class="container">
      <div class="column col-10 col-mx-auto">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobyflip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/whaler.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobyflip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/header' %>
    <div class="pad"></div>
    <div class="container">
      <div class="column col-10 col-mx-auto">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/whalers/_whaler.html.erb
<div class="card">
  <div class="card-header">
    <div class="tile tile-centered">
      <% if whaler_image_activated?(@captain) %>
      <div class="tile-icon">
        <figure class="avatar avatar-xl">
          <img src="<%= @whaler.image_url %>" alt="...">
        </figure>
      </div>
      <% end %>
      <div class="tile-content">
        <h4><%= @whaler.name %></h4>
      </div>
    </div>

  </div>
  <div class="card-body">
    <h6>Famous last words</h6>
    <blockquote>
      <%= @whaler.description %>
    </blockquote>
  </div>
  <div class="card-footer">
    <%= link_to "Message #{@whaler.email}", "mailto:#{@whaler.email}", class: 'btn btn-default' %>
  </div>
</div>

app/views/whalers/show.html.erb
<h1>Whaler Dashboard</h1>


<h3>Details</h3>
<%= render @whaler %>


<div class="pad"></div>

<h3>Recruitment Score</h3>
<div class="card">
  <div class="card-header">
    <%= @whaler.recruit_score %>
  </div>
  <div class="card-footer">
    <% if recruitment_activated?(@captain) %>
    <%# some rails form %>
    <%= link_to 'Add whaler to Pequod', '#', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>